#!/bin/bash

# exit immediately if a command fails
set -e

ECC=../saturation

if [ ! -x ${ECC} ]; then echo "run \"make\" first, then try again"; exit -1; fi

for f in 15of16 on zero
do
  echo ------------
  echo testing $f
  ${ECC} $f
  echo ------------
done
